apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: excellence-nettoyage-api #application name
    version: v0.0.7
  name: excellence-nettoyage-api #pod's name
  namespace: default
spec:
  replicas: 1 #number of pods
  minReadySeconds: 45 #give thc container to wait 45 seconds to get ready
  selector:
    matchLabels:
      app: excellence-nettoyage-api
      version: v0.0.7
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: excellence-nettoyage-api
        version: v0.0.7
    spec:
      containers:
        - image: edvilla/excellence-api:v0.0.7
          imagePullPolicy: Always
          name: excellence-nettoyage-api
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_URL
                  name: excellence-nettoyage-secret
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USERNAME
                  name: excellence-nettoyage-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: excellence-nettoyage-secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: excellence-nettoyage-secret
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  key: API_KEY
                  name: excellence-nettoyage-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: excellence-nettoyage-api
  name: excellence-nettoyage-api
  namespace: default
spec:
  ports:
    - port: 8000 #external port
      protocol: TCP
      targetPort: 8080 #api port
  selector:
    app: excellence-nettoyage-api
  sessionAffinity: None
  type: NodePort