apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ena-backend-config
  namespace: default
spec:
  healthCheck:
    checkIntervalSec: 30
    port: 8080
    type: HTTP
    requestPath: /excellence-nettoyage/api/actuator/health